### ISSUE TITLE
Auth0 Login Issue

### ISSUE THREAD

**Issue by lakhansamani** [rnplay/rnplay-reindex#2]
In order to login using Auth0 we need to specify "Allowed Callback URLs" where the user will be redirected after login. Currently, the page from where we allow a user to login has dynamic url "http://localhost:3000/apps/appid". Now each and every page with application id is not specified in "Allowed callback urls" of Auth0 so it creates problem while redirecting user

Example:
My allowed callback url is "http://localhost:3000/apps/abcde" and when I create new application it might have url as "http://localhost:3000/apps/123" so this will not allow user to login as last url was not mentioned in our Auth0 allowed callback urls.

**Comment by jsierles** [comment]
We should handle the callback in a react router onenter hook on the top level route. This way we can catch logins from anywhere. I can add this tomorrow as I already implemented it elsewhere. We can include a 'redirect to' URL to bring the user back to the app screen.
